apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: uncleboss12/udagram-api-feed:v1
        ports:
         - containerPort: 8080
        envFrom:
         - configMapRef:
             name: udagram-env
         - secretRef:
             name: udagram-db-env
        volumeMounts:
          - mountPath: "/root/.aws/"
            name: udagram-aws
      volumes:
        - name: udagram-aws
          configMap:
            name: udagram-aws 

         